- name: Install apt packages (this can take a while)
  ansible.builtin.apt:
    state: latest
    update_cache: true # equivalent of apt update
    name:
      # todo to wszystko trzeba przejrzeć, pewnie dużo usunąć i rozbić na mniejsze role
      # Ubuntu.base.base
      - sudo
      - mongodb
      - python3
      - python3-pip
      - gcc-10
      - g++-10

- name: Set default compilers and clang formater
  community.general.alternatives:
    name: "{{item.name}}"
    link: '{{"/usr/bin/" + item.name}}'
    path: "{{item.path}}"
    priority: 0
  loop:
    - { name: "gcc", path: "/usr/bin/gcc-10" }
    - { name: "g++", path: "/usr/bin/g++-10" }
