- name: Install nginx configuration files
  become: true
  template:
    dest: "{{ item.dest }}"
    group: "{{ nginx_file_nginx_config_group }}"
    mode: "{{ nginx_file_nginx_config_mode }}"
    owner: "{{ nginx_file_nginx_config_owner }}"
    src: "{{ item.src }}"
  notify: Reload nginx
  with_items: "{{ nginx_file_nginx_config }}"