- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: "{{ nginx_task }}.yml"
  with_items: "{{ nginx_task_manager }}"
  loop_control:
    loop_var: nginx_task